title: Shouzhi Xia
logo: docs/assets/photo_new.jpg
description: >
  Assistant Professor, Hunan University, China
  <br>
  <a href="mailto:kennethxia93@hotmail.com">Email</a> ·
  <a href="https://scholar.google.com/citations?hl=en&user=_0K3XCwAAAAJ&view_op=list_works&sortby=pubdate" target="_blank" rel="noopener">Google Scholar</a> ·
  <a href="https://www.researchgate.net/profile/Shouzhi-Xia?ev=hdr_xprf"_blank" rel="noopener">ResearchGate</a>
  <br><br><br><br>
  <img src="docs/assets/journal_coverpage.png" 
     alt="Journal covers" 
     style="max-width: 100%; height: auto; width: 100px; display: block; margin: 0 auto; border-radius: 10px;">
#show_downloads: true
assets:
  stylesheet: /assets/style.scss
github:
  is_project_page: false
theme: jekyll-theme-minimal
